"""Type definitions"""

from .config import (
    TaskStatus,
    ProgressEvent,
    ConversionProgressEvent,
    RateLimitInfo,
    RateLimits,
    ConversionToolsConfig,
    ConversionInput,
    ConvertOptions,
    WaitOptions,
    TaskStatusResponse,
    TaskCreateRequest,
    TaskCreateResponse,
    FileUploadResponse,
    FileInfo,
    FileUploadOptions,
    UserInfo,
    FileSource,
    FileResult,
    TaskDetail,
)

__all__ = [
    "TaskStatus",
    "ProgressEvent",
    "ConversionProgressEvent",
    "RateLimitInfo",
    "RateLimits",
    "ConversionToolsConfig",
    "ConversionInput",
    "ConvertOptions",
    "WaitOptions",
    "TaskStatusResponse",
    "TaskCreateRequest",
    "TaskCreateResponse",
    "FileUploadResponse",
    "FileInfo",
    "FileUploadOptions",
    "UserInfo",
    "FileSource",
    "FileResult",
    "TaskDetail",
]
